# Generated by Django 3.2.3 on 2021-05-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondstep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=50)),
                ('title_eng1', models.CharField(max_length=50)),
                ('title_eng2', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='realimage')),
            ],
        ),
        migrations.DeleteModel(
            name='Objects',
        ),
    ]
