# Generated by Django 3.2.3 on 2021-05-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondstep', '0002_auto_20210517_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='realimage')),
            ],
        ),
        migrations.AlterField(
            model_name='object',
            name='photo',
            field=models.ImageField(upload_to='illust'),
        ),
    ]
