# Generated by Django 3.2.2 on 2021-05-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondstep', '0003_auto_20210517_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='title_eng1',
            new_name='title_eng',
        ),
        migrations.RemoveField(
            model_name='object',
            name='title_eng2',
        ),
    ]
