# Generated by Django 3.2.2 on 2021-05-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondstep', '0004_auto_20210518_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='illust'),
        ),
    ]
