# Generated by Django 3.2.2 on 2021-05-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondstep', '0005_alter_object_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='photo',
            new_name='illust',
        ),
    ]
