# Generated by Django 3.2.2 on 2021-05-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondstep', '0006_rename_photo_object_illust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userobject',
            name='title_kor',
        ),
    ]
